# Optimización de Rendimiento
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin & KSP Performance
kotlin.code.style=official
android.disallowKotlinSourceSets=false
ksp.incremental=true
ksp.incremental.log=false

# Compose
android.defaults.buildfeatures.buildconfig=true
